### ISSUE TITLE
 cannot unmarshal hex string without 0x prefix into Go struct fieild error

### ISSUE THREAD

**Issue by JYama321** [EthWorks/ethereum.rb#101]
When sending json-rpc request, this happens. 
I think when creating abi  like` sha3(<function>) `,  _0x_ have to be added as prefix.

**Comment by kurotaky** [comment]
@JYama321 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
