### ISSUE TITLE
Sending ether together with a function call?

### ISSUE THREAD

**Issue by alex-kampa** [EthWorks/ethereum.rb#103]
Does anyone here know how to send ether to a contract, together with a function call?

**Comment by allush** [comment]
I have same question. I need to call (transact) payable method of contract, but I dont know how to pass Ether value.

**Comment by kurotaky** [comment]
@alex-kampa 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
