### ISSUE TITLE
Byte type is encoded unexpectedly

### ISSUE THREAD

**Issue by toshiboy86** [EthWorks/ethereum.rb#104]
When executing a method with arguments of data-type `bytes`,
 a method `encode_bytes(value, subtype) in encoder.rb` is called in the process, and eventually pass encoded bytes data to a smart contract, which ends up in the situation that only encoded parameter is available in smart contract side.

All I want to do is passing the argument below as it is not being encoded.

`@interface.transact.method_name("0x0000000000000000000000000000000000sample")`

Is there any tips or solution ? 

--------
ethereum.rb/lib/ethereum/encoder.rb
https://github.com/EthWorks/ethereum.rb/blob/master/lib/ethereum/encoder.rb

**Comment by toshiboy86** [comment]
@swraife 
Probably turning hex data into binary works.
Try this and pass the return data
`Eth::Utils.hex_to_bin(your_hex_data)`

**Comment by kurotaky** [comment]
@toshiboy86 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
