### ISSUE TITLE
Contract transact_and_wait error: undefined method [] for nil:NilClass

### ISSUE THREAD

**Issue by veejar** [EthWorks/ethereum.rb#109]
Hello

Tested calling contract method on Kovan Test Network:
`contract.transact_and_wait.transfer(some_eth_addr, wei_amount)`
and got error:
`undefined method [] for nil:NilClass`

**Trace:**
```
ethereum.rb (2.2) lib/ethereum/transaction.rb:24:in `mined?'
ethereum.rb (2.2) lib/ethereum/transaction.rb:31:in `block in wait_for_miner'
ethereum.rb (2.2) lib/ethereum/transaction.rb:29:in `loop'
ethereum.rb (2.2) lib/ethereum/transaction.rb:29:in `wait_for_miner'
ethereum.rb (2.2) lib/ethereum/contract.rb:199:in `transact_and_wait'
ethereum.rb (2.2) lib/ethereum/contract.rb:325:in `block (2 levels) in create_function_proxies'
```
Issue is relate to this code line:
https://github.com/EthWorks/ethereum.rb/blob/master/lib/ethereum/transaction.rb#L24

Looks like simplest solution is:
```
@mined =
    @connection.eth_get_transaction_by_hash(@id)["result"]["blockNumber"].present? rescue false
```

**Comment by DavidMMelin** [comment]
Any update on this? I'm getting this error, causing a failure and sending the transaction again, but it looks like the transfer actually succeeds

**Comment by glitch003** [comment]
I fixed this issue on my fork: https://github.com/deconet/ethereum.rb

**Comment by kurotaky** [comment]
@veejar 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
