### ISSUE TITLE
Problem with digest-sha3 gem on Ubuntu 16.04

### ISSUE THREAD

**Issue by Eugenpaul** [EthWorks/ethereum.rb#11]
Hello
It seems that you have a dependency, that causes this error at least on Ubuntu 16.04:
```
Building native extensions.  This could take a while...
ERROR:  Error installing digest-sha3:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/digest-sha3-1.1.0/ext/digest
/usr/bin/ruby2.3 -r ./siteconf20170706-6882-10kgp7b.rb extconf.rb
checking for ruby/digest.h... yes
checking for rb_str_set_len()... yes
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/digest-sha3-1.1.0/mkmf.log

current directory: /var/lib/gems/2.3.0/gems/digest-sha3-1.1.0/ext/digest
make "DESTDIR=" clean

current directory: /var/lib/gems/2.3.0/gems/digest-sha3-1.1.0/ext/digest
make "DESTDIR="
compiling KeccakF-1600-reference.c
compiling KeccakNISTInterface.c
compiling KeccakSponge.c
compiling displayIntermediateValues.c
displayIntermediateValues.c: In function ‘displayText’:
displayIntermediateValues.c:113:9: error: format not a string literal and no format arguments [-Werror=format-security]
         fprintf(intermediateValueFile, text);
         ^
cc1: some warnings being treated as errors
Makefile:239: recipe for target 'displayIntermediateValues.o' failed
make: *** [displayIntermediateValues.o] Error 1

make failed, exit code 2
```

The gem is no longer maintained. But looks like solution proposed here by lmX2015 works: https://github.com/phusion/digest-sha3-ruby/issues/7

**Comment by marekkirejczyk** [comment]
Thank you for research. Would you be interested in doing PR?

**Comment by Eugenpaul** [comment]
The fix should be added in the other gem. I tried creating a [pull request](https://github.com/phusion/digest-sha3-ruby/pull/8) there, but don't know if the maintainer accepts it anytime soon.

**Comment by adrianov** [comment]
I can suggest replacing digest-sha3 with sha3 gem, which doesn't have this issue.

**Comment by litch** [comment]
This is also an issue for ubuntu 14.04, FWIW.

**Comment by marekkirejczyk** [comment]
@adrianov Would you like to do a PR?

**Comment by se3000** [comment]
Was looking into this for ruby-eth, and unfortunately the sha3 gem is not a simple drop in to replace for digest-sha3. Specifically, sha3 is FIPS-202 compliant, but Ethereum uses a non FIPS-202 compliant version which digest-sha3 also uses.

More detail on the differences [here](https://ethereum.stackexchange.com/questions/550/which-cryptographic-hash-function-does-ethereum-use), but I believe Ethereum chose their algo before the SHA3 standard was finalized.

**Comment by kurotaky** [comment]
I think this library(digest-sha3) is not maintained 😢

**Comment by q9f** [comment]
> Was looking into this for ruby-eth, and unfortunately the sha3 gem is not a simple drop in to replace for digest-sha3. Specifically, sha3 is FIPS-202 compliant, but Ethereum uses a non FIPS-202 compliant version which digest-sha3 also uses.

You can use `keccak`: https://github.com/q9f/keccak.rb

> I think this library(digest-sha3) is not maintained cry

It's the same gem but maintained by me. https://rubygems.org/gems/keccak
