### ISSUE TITLE
Incorrect nonce when changing private key

### ISSUE THREAD

**Issue by longhoangwkm** [EthWorks/ethereum.rb#111]
```ruby
class EthereumClient
  ETHEREUM_NETWORK_URL = ENV.fetch('ETHEREUM_NETWORK_URL')

  def self.client
    return @client if @client

    @client = Ethereum::HttpClient.new(ETHEREUM_NETWORK_URL)
    @client.default_account = '0xaaaa'
    @client
  end
```

```ruby
class SmartContract
  attr_accessor :contract_instance

  def initialize(name, address, code, abi)
    @contract_instance = Ethereum::Contract.create(
      name: name,
      address: address,
      code: code,
      abi: abi,
      client: EthereumClient.client
    )
  end

  def transfer(from_private_hex, to_address, amount)
    key = Eth::Key.new priv: from_private_hex
    @contract_instance.key = key
    @contract_instance.transact.transfer__address__uint256(to_address, amount)
  end
```

```ruby
contract = SmartContract.new(NAME, ADDRESS, CODE, ABI)
contract.transfer(from_private_hex, to_address, amount)
```
I have multi account A,B, C
When i wanna transfer token from account A,B,C to D.
It worked as well.
But when i create tx for B. B's tx nonce get nonce number from A. It should be change nonce when i assign a new private_key

**Comment by longhoangwkm** [comment]
I found the cause here: `https://github.com/EthWorks/ethereum.rb/blob/master/lib/ethereum/contract.rb#L123`
```ruby
      @nonce ||= @client.get_nonce(key.address) - 1
      @nonce += 1
```
I knew this way (||=) to avoid query again to network.
But it should be 
```ruby
      @nonce = @client.get_nonce(key.address)
```

**Comment by longhoangwkm** [comment]
Can i make a PR ?!

**Comment by codeandgraphics** [comment]
Seems like still not fixed. 
Guys, do you know that blockchain nonce can change somewhere outside?
You SHOULD request nonce before every transaction

**Comment by longhoangwkm** [comment]
i have no problem with that PR. Nonce is requested before every transaction with new code

**Comment by codeandgraphics** [comment]
@longhoangwkm your PR works as expected)

**Comment by kurotaky** [comment]
@longhoangwkm 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
