### ISSUE TITLE
Compatibility with JRuby

### ISSUE THREAD

**Issue by QuentinCazelles** [EthWorks/ethereum.rb#115]
Hi everybody !

I would like to ask if this library is compatible with JRuby (the Java implementation of Ruby).

According to me it is not because of digest-sha3 which is a C extension. But I am a beginner in Ruby.

I managed to make it work by switching digest-sha3 for keccak-pure-ruby in ethereum.rb but also in its dependency eth which also uses digest-sha3.

I would like a proper solution to make this library work with JRuby. Would you have any idea how I can manage that please ?

Is there any new maintainer yet )= ?

Thank you !

**Comment by oshanz** [comment]
found this pure ruby gem https://github.com/havenwood/sha3-pure-ruby

**Comment by QuentinCazelles** [comment]
Thank you for your answer and thank you for reminding me this thread.
I actually used the keccak pure ruby gem : https://github.com/ciri-ethereum/keccak-pure-ruby.
I believe it works at least as good as yours !
Thank you !
