### ISSUE TITLE
Error ends_with? in abi.rb

### ISSUE THREAD

**Issue by QuentinCazelles** [EthWorks/ethereum.rb#116]
Hello !

In abi.rb we can find the line : 
`raise NotImplementedError if type.ends_with?("]")`

type is a string.
I had to rename ends_with? with end_with? according to the ruby string api.

Can I make a PR or do I do something wrong please ??

Thank you !

**Comment by kurotaky** [comment]
Hello! `ends_with?` is activesupport methods.

> Active Support defines 3rd person aliases of String#start_with? and String#end_with?:

https://guides.rubyonrails.org/v5.0/active_support_core_extensions.html#starts-with-questionmark-and-ends-with-questionmark
