### ISSUE TITLE
Bug with present? ?

### ISSUE THREAD

**Issue by QuentinCazelles** [EthWorks/ethereum.rb#117]
I managed to make the decoder working by changing "subtype.present?" by "!subtype.blank?"

Don't know what the error really is. I know there is no maintainer but I wanted to leave a trace here (=

**Comment by kurotaky** [comment]
@QuentinCazelles 
thanks for your report! 
Can you show the behavior of the error in the following format?
```
### Steps to reproduce
<!-- Steps to reproduce the behavior -->

### Expected behavior
<!-- Tell us what should happen -->

### Actual behavior
<!-- Tell us what happens instead -->

### System configuration
**Ruby version**:
**Solc version**:
**Parity version**:
**OS**:

### Failure Logs
<!-- Please include any relevant log snippets or files here-->
```

**Comment by QuentinCazelles** [comment]
### Steps to reproduce
```ruby
require './lib/ethereum.rb/lib/ethereum/decoder'
decoder = Decoder.new
value = decoder.decode_uint(0x000000000000000000000000000000000000000000000000000000000000000a)
puts value
```

### Expected behavior
Should print 10 as "a" in hex is 10.

### Actual Behavior
Raises a NoMethodError

### System configuration

ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

solc, the solidity compiler commandline interface
Version: 0.8.13+commit.abaa5c0e.Linux.g++

Geth
Version: 1.10.17-unstable
Git Commit: eb3ebceaa112dc62bbe5751e721c1d6c90bc50fb
Architecture: amd64
Go Version: go1.18
Operating System: linux

Linux 5.14.0-1031-oem #34-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

### Failures logs

```
ruby main.rb
Traceback (most recent call last):
        2: from main.rb:3:in `<main>'
        1: from /something/lib/ethereum.rb/lib/ethereum/decoder.rb:33:in `decode_uint'
/something/lib/ethereum.rb/lib/ethereum/decoder.rb:86:in `bitsize': undefined method `present?' for "256":String (NoMethodError)
Did you mean?  prepend
```

Thank you

**Comment by kurotaky** [comment]
@QuentinCazelles 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
