### ISSUE TITLE
Ethereum::Decoder wrongly modifies bytes value

### ISSUE THREAD

**Issue by unlimit** [EthWorks/ethereum.rb#118]
Bytes decoder modifies output by removing leading and trailing whitespaces!
Example: 
`value = "0x8462e7f0b47b62675ccb013ce1a9930bb3fad566d2d51c66cbead62e64d85f090000"`
`res = Ethereum::Decoder.new.decode_bytes(value, 32, 2)`
=>`"\x84b\xE7\xF0\xB4{bg\\\xCB\x01<\xE1\xA9\x93\v\xB3\xFA\xD5f\xD2\xD5\x1Cf\xCB\xEA\xD6.d\xD8_"`

But it should return:
`"\x84b\xE7\xF0\xB4{bg\\\xCB\x01<\xE1\xA9\x93\v\xB3\xFA\xD5f\xD2\xD5\x1Cf\xCB\xEA\xD6.d\xD8_\t"`

**Comment by kurotaky** [comment]
I didn't know why this change was necessary.
If you still need this change, please report in the following format:

```
### Steps to reproduce
<!-- Steps to reproduce the behavior -->

### Expected behavior
<!-- Tell us what should happen -->

### Actual behavior
<!-- Tell us what happens instead -->

### System configuration
**Ruby version**:
**Solc version**:
**Parity version**:
**OS**:

### Failure Logs
<!-- Please include any relevant log snippets or files here-->

```
