### ISSUE TITLE
Path to geth.ipc not set for linux

### ISSUE THREAD

**Issue by Eugenpaul** [EthWorks/ethereum.rb#12]
Hi
When running geth on Ubuntu my paths to .ipc file are ~/.ethereum/geth.ipc and ~/.ethereum/testnet/geth.ipc. As I can see IpcClient doesn't have those paths in its list. It causes an error when trying to open a contract. The same error can be seen if I run rake ethereum:test:setup:
```
>rake ethereum:test:setup
rake aborted!
Errno::EINVAL: Invalid argument - connect(2) for 
<...>/ethereum.rb/lib/ethereum/ipc_client.rb:27:in `initialize'
<...>/ethereum.rb/lib/ethereum/ipc_client.rb:27:in `new'
<...>/ethereum.rb/lib/ethereum/ipc_client.rb:27:in `send_single'
<...>/ethereum.rb/lib/ethereum/client.rb:126:in `send_command'
<...>ethereum.rb/lib/ethereum/client.rb:137:in `block (2 levels) in <class:Client>'
<...>/ethereum.rb/lib/tasks/ethereum_test.rake:8:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => ethereum:test:setup
```
For some reason it affects HttpClient as well. My workaround now is to create a simlink from one of the existing paths. The solution would probably be to hardcode two more paths: "#{ENV['HOME']}/.ethereum/geth.ipc" and ""#{ENV['HOME']}/.ethereum/testnet/geth.ipc", - but I'm not sure. Is there a way to set the path with HttpClient?

**Comment by marekkirejczyk** [comment]
Adding path sounds like a good solution. Would like to do a PR?

Should not affect HttpClient, would you provide steps to reproduce?

**Comment by Eugenpaul** [comment]
HttpClient is fine, my bad. I forgot to set the client when creating a contract.
And yes, I'll create a PR

**Comment by marekkirejczyk** [comment]
@Eugenpaul Great job, all merged, thank you.
