### ISSUE TITLE
how we can use on test network ropsten, rinkeby

### ISSUE THREAD

**Issue by Avdhesh51000** [EthWorks/ethereum.rb#129]
I am trying to connect with infura 
Creating clinent like

> Client = Ethereum::HttpClient.new("https://ropsten.infura.io/v3/5xxxxxxxxxxxxdb")

And trying to deploy account like

> contract_instance = Ethereum::Contract.create(file: "abc.sol",client: Client)

or even if i am trying to import_raw_key or creating new personal account its give same error

> JSON::ParserError (767: unexpected token at 'account disabled)

**Comment by kurotaky** [comment]
If you still get the error, Can you show the behavior of the error in the following format?
```
### Steps to reproduce
<!-- Steps to reproduce the behavior -->

### Expected behavior
<!-- Tell us what should happen -->

### Actual behavior
<!-- Tell us what happens instead -->

### System configuration
**Ruby version**:
**Solc version**:
**Parity version**:
**OS**:

### Failure Logs
<!-- Please include any relevant log snippets or files here-->
```

**Comment by kurotaky** [comment]
@Avdhesh51000 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
