### ISSUE TITLE
Support for Diamonds

### ISSUE THREAD

**Issue by mudgen** [EthWorks/ethereum.rb#143]
It would be great if ethereum.rb provided support for deploying and upgrading diamonds. The Diamond Standard is here: https://github.com/ethereum/EIPs/issues/2535

"A diamond is a set of contracts that can access the same storage variables and share the same Ethereum address."

Here is an example of a tool (in Python) that helps manage diamonds: https://github.com/lampshade9909/DiamondSetter

Blog post about that tool: http://joeyzacherl.com/2020/06/diamond-setter-ethereum-smart-contract-manager/

**Comment by kurotaky** [comment]
@mudgen 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
