### ISSUE TITLE
OpenSSL 1.1.1 compatible?

### ISSUE THREAD

**Issue by jpmermoz** [EthWorks/ethereum.rb#160]
Hi there,

I'm getting the following error when I try to sign a message:

FFI::NotFoundError (Function 'SSL_library_init' not found in [libssl.so])

I'm using Ruby 3 and the following gems:

gem 'digest-sha3', git: 'https://github.com/makevoid/digest-sha3-ruby', ref: '887b1051dd8d642ad9b16ea2ba075e3463051d83'
gem 'eth'

Thank you!

**Comment by longhoangwkm** [comment]
@jpmermoz https://github.com/longhoangwkm/ruby-eth/commit/269c58d4aebca2d557ae29a0259b8b3d10c1aca1
You can take a look. I upgraded dependence lib ruby-eth to avoid above error.

**Comment by jpmermoz** [comment]
@longhoangwkm thanks! I'll try it :)

**Comment by q9f** [comment]
This is fixed with `eth >= 0.5.0`.

**Comment by kurotaky** [comment]
@jpmermoz 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
