### ISSUE TITLE
Interacting with ERC20 proxy contracts

### ISSUE THREAD

**Issue by davide-scalzo** [EthWorks/ethereum.rb#161]
Hi all,

I'd like to be able to programmatically send USDT and USDC tokens. I've got an implementation in place that seems to work fine on Rinkeby for USDT.

However I am struggling with USDC as it is a proxy contract as seen here https://etherscan.io/address/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48#readContract

Whatever method on the contract I am trying to call I get `undefined method`, for example

```
client = initialize_client() // Creates infura based httpclient
file = File.read('./app/services/ethereum_abis/usdc.json')
abi = JSON.parse(file)
contract = Ethereum::Contract.create(name: "FiatTokenProxy", address: ENV['USDC_CONTRACT_ADDRESS'], abi: abi.to_json, client: client)
balance = contract.call.balance_of(ENV['ETHEREUM_SEND_ACCOUNT'])
```
Returns `NoMethodError: undefined method `balance_of' for #<#<Class:0x0000558de09d03f0>:0x0000558de09ddc80>`

That seems to be because
```
[development] main:0> (contract.call.methods - Object.methods).sort
=> [:admin, :change_admin, :implementation, :upgrade_to, :upgrade_to_and_call]
```

The call class only has access to the outside implementation method, but how can we retrieve the relevant implementation contract using this library? I guess would be possible to hardcode the actual implementation contract, but it would be safer to reference it from the main contract.

Any help would be super appreciated!

**Comment by kurotaky** [comment]
@davodesign84 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
