### ISSUE TITLE
ethereum:node:test gives Invalid address: "--author" with author set to an address

### ISSUE THREAD

**Issue by s2sv** [EthWorks/ethereum.rb#164]
### Steps to reproduce
Installed all prerequisites

### Expected behavior
Ethereum node should start

### Actual behavior
Invalid address: "--author"

### System configuration
**Ruby version**: '3.0.1' with gem 'digest-sha3'
**Solc version**: 0.5.16+commit.9c3226ce.Linux.g++
**Parity version**: v2.7.2-stable
**OS**: Ubuntu 20.04

### Failure Logs
rake ethereum:node:test --trace
** Invoke ethereum:node:test (first_time)
** Execute ethereum:node:test
parity --chain testnet --password ~/Library/Application\ Support/io.parity.ethereum/pass --unlock  --author 
Loading config file from /home/user/snap/parity/16707/.local/share/io.parity.ethereum/config.toml
Invalid address: "--author"

### config.toml

[account]
unlock = ["0xADDRESS"]
password = ["/home/user/snap/parity/16707/.local/share/io.parity.ethereum/password"]

[mining]
author = "0xADDRESS"

**Comment by kurotaky** [comment]
@s2sv 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
