### ISSUE TITLE
Error installing ethereum.rb with ruby>=3

### ISSUE THREAD

**Issue by marek22k** [EthWorks/ethereum.rb#172]
I'm using Ruby>= 3 and ethereum.rb installation fails:
ERROR: While executing gem ... (NoMethodError)
     undefined method `request 'for nil: NilClass

### Steps to reproduce
Install ruby >= 3 and run `gem install ethereum.rb-2.5.gem`

### Expected behavior
As with ruby = 2
```
Successfully installed ethereum.rb-2.5
Parsing documentation for ethereum.rb-2.5
Done installing documentation for ethereum.rb after 0 seconds
1 gem installed
```

### Actual behavior
It returns:
```
ERROR:  While executing gem ... (NoMethodError)
    undefined method `request' for nil:NilClass
```

### System configuration
**Ruby version**:
  ruby3 - ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
  ruby2 - ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]

**OS**: Parrot OS Home (Debian 11 fork)

**Comment by empeje** [comment]
Up this is important to support newer ruby version.

**Comment by empeje** [comment]
@marek22k for now you can fix this by pointing directly to the commit id

```ruby
gem 'ethereum.rb', :git => "https://github.com/EthWorks/ethereum.rb.git", ref: "4a81fed12f0698627638f3e70acf05a261712b21"
```

**Comment by sg552** [comment]
@empeje   seems your patch would throw exception when using `eth` gem, which is still using Ruby `2.x`

**Comment by empeje** [comment]
@sg552 which actions that will throw an exception? I tried with my little Rails 6 + Ruby 3 app and both ruby-eth and ethereum.rb works just fine, or maybe I haven't use more advance feature.

**Comment by sg552** [comment]
I faild to install `eth` gem under ruby 3.0,    



![图片](https://user-images.githubusercontent.com/234533/148679378-5cf391f1-7db9-4d75-9b91-4550439b8802.png)

**Comment by q9f** [comment]
@sg552 yes, you would need to manually install `money-tree`, unfortunately.

https://github.com/GemHQ/money-tree/issues/50#issuecomment-1004835258

Or, use the 0.5 branch of `eth` which does not rely on money-tree. https://github.com/q9f/eth.rb

**Comment by marek22k** [comment]
> @marek22k for now you can fix this by pointing directly to the commit id
> 
> ```ruby
> gem 'ethereum.rb', :git => "https://github.com/EthWorks/ethereum.rb.git", ref: "4a81fed12f0698627638f3e70acf05a261712b21"
> ```
> 
> commit id [4a81fed](https://github.com/EthWorks/ethereum.rb/commit/4a81fed12f0698627638f3e70acf05a261712b21)

```
$gem 'ethereum.rb', :git => "https://github.com/EthWorks/ethereum.rb.git", ref: "4a81fed12f0698627638f3e70acf05a261712b21"
-bash: https://github.com/EthWorks/ethereum.rb.git,: No such file or directory
```
Unfortunately this doesn't seem to be working for me.

**Comment by empeje** [comment]
@marek22k it is meant for your Gemfile not for a bash command.

**Comment by kurotaky** [comment]
@marek22k 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
