### ISSUE TITLE
invalid or missing value for params[1]

### ISSUE THREAD

**Issue by Stan-Wang** [EthWorks/ethereum.rb#18]
There is an error when I try to use transfer from Client.

`client.transfer(k2,'addess1',1)`
`
IOError: invalid or missing value for params[1]
	from (irb):3
`

It seems like https://github.com/ethereum/go-ethereum/issues/2472
Is there something wrong with eth_send_raw_transaction ？

**Comment by kurotaky** [comment]
@Stan-Wang 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
