### ISSUE TITLE
Can't resolve ActiveSupport version if the project uses a version newer than 5.0.1 (for example RubyOnRails v7 projects)

### ISSUE THREAD

**Issue by nizovtsevnv** [EthWorks/ethereum.rb#182]
Update gem on rubygems repository please.

### Steps to reproduce

Make a Gemfile for Rails v7 (which using ActiveSupport v7):
```
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.0"

gem "rails", "~> 7.0.1"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem 'ethereum.rb'
```

And try to install gems with `bundle install`

It works only if I use the git master branch: `gem 'ethereum.rb', github: 'EthWorks/ethereum.rb'`

### Expected behavior

`Bundle complete! ...`

### Actual behavior

```
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    ethereum.rb was resolved to 2.0.2, which depends on
      activesupport (~> 5.0.1)

    rails (~> 7.0.1) was resolved to 7.0.1, which depends on
      activesupport (= 7.0.1)
```

### System configuration
**Ruby version**: 3.0.1
**OS**: Alpine Linux

**Comment by q9f** [comment]
We could just remove active support.
