### ISSUE TITLE
IOError: Method not found for personal methods

### ISSUE THREAD

**Issue by istickz** [EthWorks/ethereum.rb#25]
How to call to personal methods from IPC client to Parity?

Example:

```
  client = Ethereum::IpcClient.new(partiy_ipc_path)
  client.personal_list_accounts
  => IOError: Method not found from client.rb:129:in `send_command'
Another methods works fine
```
When I'm working with IpcClient and geth, all methods works fine

**Comment by marekkirejczyk** [comment]
use following notation `personal_listAccounts`

Full list o supported commands is here:
https://github.com/EthWorks/ethereum.rb/blob/master/lib/ethereum/client.rb
