### ISSUE TITLE
activesupport ~> 5.0

### ISSUE THREAD

**Issue by keo** [EthWorks/ethereum.rb#32]
Hi,

does ethereum.rb specifically require activesupport >5.0?

why is it locked to this version?

Thank you for clarifying.

**Comment by artamonovdev** [comment]
I don't know. But with activesupport 4.1 everythings works fine.

**Comment by marekkirejczyk** [comment]
Feel free to do a PR.

**Comment by keo** [comment]
Will test it myself, if it works well with 4.x too I'll send a PR.
