### ISSUE TITLE
Trying to deploy contract with Docker container node

### ISSUE THREAD

**Issue by dilumn** [EthWorks/ethereum.rb#34]
I am having a docker container which runs `ethereum/client-go`. And it's working fine with block synchronisation.

From the container I forwarded the ports `8545` & `30303` as well.
Here is my `lsof -i :8545` output
```
COMMAND  PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
parity  6198 Admin   44u  IPv4 0xfdda6e6d4d9bbb97      0t0  TCP localhost:8545 (LISTEN)
vpnkit  6208 Admin   24u  IPv4 0xfdda6e6d4d65db97      0t0  TCP *:8545 (LISTEN)
vpnkit  6208 Admin   25u  IPv6 0xfdda6e6d4509106f      0t0  TCP localhost:8545 (LISTEN)
```

But when I'm trying to deploy a contract using `ethereum.rb` it just stuck in that step. Even though I haven't unlock any account it doesn't throw me an error saying there are no unlock account.

So do you have any idea why `ethereum.rb` can not connect with my docker container client?

**Comment by dilumn** [comment]
Now I tried to forward only `8545` as below
`ports:
      - '127.0.0.1:8545:8545'`

And now I cannot call `Ethereum::Contract.create` method. It gives me the following error,

```
/Users/Admin/.rvm/gems/ruby-2.4.0/gems/ethereum.rb-2.1.7/lib/ethereum/ipc_client.rb:30:in `initialize': Connection refused - connect(2) for /Users/Admin/Library/Application Support/io.parity.ethereum/jsonrpc.ipc (Errno::ECONNREFUSED)
```
Any idea what's happening here??

**Comment by marekkirejczyk** [comment]
Try Parity instead of ethereum go

**Comment by dilumn** [comment]
Managed to fixed it with initializing the client with my custom ipc path
`client = Ethereum::IpcClient.new("", false)`
