### ISSUE TITLE
Class overwriting

### ISSUE THREAD

**Issue by adrianov** [EthWorks/ethereum.rb#36]
Hi all,

I am writing Rails application, using Ethereum blockchain and local DB.
I have `payment_order.sol` contract and also have `PaymentOrder` ActiveRecord model.
When the contract is built and application tries to access `PaymentOrder` ActiveRecord model, it crushes, because its class is overwritten by contract class in `build` method, and no longer have ActiveRecord methods.
Changed
```
    def build
      class_name = @name.camelize
```
with
```
    def build
      class_name = @name.camelize + 'EthereumRb'
```
And it works again. But probably you can suggest better solution.

**Comment by marekkirejczyk** [comment]
1) Easy solution:
Change the name of one of the classes, e.g. `PaymentOrderContract` in solidity, or introduce namespace for activemodel class: Model::PaymentOrder 

2) More universal  solution - add a new propery to class, sth like this:
```
   attr_accessor :class_name
...
   def initialize(..., class_name =  @name.camelize )
...
   def self.create(..., @name.camelize: nil)
...
    def build
      class_name = @class_name 

```

I'll be happy to accept PR.
