### ISSUE TITLE
Weird issue with encoder?

### ISSUE THREAD

**Issue by AlexanderZaytsev** [EthWorks/ethereum.rb#40]
I have the following contract:
```solidity
pragma solidity ^0.4.4;

contract TestRecover {
  function isValidAddress(bytes32 hash, uint8 v, bytes32 r, bytes32 s) constant returns(bool) {
    return (ecrecover(hash, v, r, s) == 0x0b1A5F722A111B1903D493420Adb85c15a848CB0);
  }
}
```
When I run it from the truffle console, it returns `true`:
```javascript
TestRecover.at('0x068a489399c0488cdf14670b1ad9efff0d7f83af').isValidAddress(
'0xa1de988600a42c4b4ab089b619297c17d53cffae5d5120d82d8a92d0bb3b78f2', 
27, 
'0xf79d2e19fb416715f7b142fd2f3cbe14e6d348d068d24d4ff7ea3aec53593bae', 
'0x4cf71703542e9a966ce01b2833e695f60d6d7fad7e7bf171df74cc3c0969acc4')
```
When I run through the gem, it returns `false`:
```ruby
client = Ethereum::HttpClient.new('http://localhost:8545')
contract = Ethereum::Contract.create(name: "TestRecover", address: "0x068a489399c0488cdf14670b1ad9efff0d7f83af", client: client, abi: JSON.parse(open('/contracts/TestRecover.json').read)['abi'])
contract.call.is_valid_address(
'0xa1de988600a42c4b4ab089b619297c17d53cffae5d5120d82d8a92d0bb3b78f2', 
27, 
'0xf79d2e19fb416715f7b142fd2f3cbe14e6d348d068d24d4ff7ea3aec53593bae', 
'0x4cf71703542e9a966ce01b2833e695f60d6d7fad7e7bf171df74cc3c0969acc4')
# false
```

I set `log` to true to see what params are getting sent to `eth_call` by the gem, and then used them in truffle console:
```
web3.eth.call({"to":"0x068a489399c0488cdf14670b1ad9efff0d7f83af","from":"0x0b1A5F722A111B1903D493420Adb85c15a848CB0","data":"0x48b8e303307861316465393838363030613432633462346162303839623631393239376331376435336366666165356435313230643832643861393264306262336237386632000000000000000000000000000000000000000000000000000000000000001b307866373964326531396662343136373135663762313432666432663363626531346536643334386430363864323464346666376561336165633533353933626165307834636637313730333534326539613936366365303162323833336536393566363064366437666164376537626631373164663734636333633039363961636334"})
```
This also returns false, so obviously the problem is in encoding the `data` field.
What might be the issue here?

**Comment by jezhiggins** [comment]
I've just been tracking down the same problem.  There's a bug in the binary to hex conversion encoding bytes.  It has been fixed in the repository, but the fix has not yet been released.  Work around is to build and install the gem locally, I guess.

**Comment by jezhiggins** [comment]
Specifically, Ethereum::encoder::encode_static_bytes wasn't zero-passing the converted hex values - 
2.1.7 release has  
    def encode_static_bytes(value)
      value.each_char.map {|x| x.ord.to_s(16) }.join("").ljust(64, '0')
    end

corrected version is 

     def encode_static_bytes(value)
         value.bytes.map {|x| x.to_s(16).rjust(2, '0')}.join("").ljust(64, '0')
     end

There's a similar issue & fix in encode_string.

They appear to have been committed pretty immediately after the 2.1.7 gem was released.

**Comment by marekkirejczyk** [comment]
@jezhiggins Would you do a PR?

**Comment by jezhiggins** [comment]
I don't need to :) - the fix already exists in the master branch, it just hasn't yet been released.

**Comment by marekkirejczyk** [comment]
Good point new version pushed to ruby gems :)

**Comment by jezhiggins** [comment]
Thanks!

**Comment by AlexanderZaytsev** [comment]
Unfortunately it didn't fix my problem, so there must be another bug somewhere.
