### ISSUE TITLE
testrpc

### ISSUE THREAD

**Issue by markmcdonald51** [EthWorks/ethereum.rb#43]
Hi!

Thanks for creating and sharing this gem. I am trying to make use of it so I compiled parity, and installed solc.

invalid argument  connect(2)

line 21 of the controller.
on Etherem::contract.create

It seems to be compiling the contract sol file but I am not sure what I am missing. Wondering if this is possible to use just bypass and use testrpc with you gem for testing? 

Thanks in advance!
Mark

**Comment by ToJen** [comment]
did you try tesrpc?

**Comment by kurotaky** [comment]
If you are still error now, Can you show the behavior of the error in the following format?
```
### Steps to reproduce
<!-- Steps to reproduce the behavior -->

### Expected behavior
<!-- Tell us what should happen -->

### Actual behavior
<!-- Tell us what happens instead -->

### System configuration
**Ruby version**:
**Solc version**:
**Parity version**:
**OS**:

### Failure Logs
<!-- Please include any relevant log snippets or files here-->
```

**Comment by kurotaky** [comment]
@markmcdonald51 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
