### ISSUE TITLE
Examples on Listening for Events

### ISSUE THREAD

**Issue by therevoltingx** [EthWorks/ethereum.rb#45]
Hi,

Currently using this project but having difficulty implementing event logs.
I need to be able to listen for events and decode its data, but there is no documentation on how to do it.

Thank you.

**Comment by JohnSmall** [comment]
I see no one has replied. I'll be listening for events soon so I'll do my best to work through it. Did you work it out at all?

**Comment by therevoltingx** [comment]
Hi @JohnSmall sorry for the late reply.

Yeah we were able to figure out how to listen for events by looking at the specs. Would have loved some documentation to go with it but so far everything's working well, even if it's not fully documented.

Thanks!

**Comment by onemanstartup** [comment]
@therevoltingx much contribution, such open source, wow, thank you

**Comment by therevoltingx** [comment]
@onemanstartup @JohnSmall 

Here's the PR that adds instructions on how to deal with Solidity events with this Gem: https://github.com/EthWorks/ethereum.rb/pull/52

**Comment by onemanstartup** [comment]
@therevoltingx now it is real thanks :) Thanks

**Comment by marekkirejczyk** [comment]
Thanks, @therevoltingx! PR merged, closing.
