### ISSUE TITLE
Problems sending erc20 token

### ISSUE THREAD

**Issue by tinbka** [EthWorks/ethereum.rb#46]
```ruby
client = Ethereum::HttpClient.new(endpoint_url)
# => #<Ethereum::HttpClient:0x0055cd7de0da80 @id=0, @log=false, @batch=nil, @formatter=#<Ethereum::Formatter:0x0055cd7de0da58>, @gas_price=1000000000, @gas_limit=4000000, @host="172.16.0.16", @port=8545, @ssl=false, @uri=#<URI::HTTP http://172.16.0.16:8545>, @default_account="0x0fe7cec4eb814b884fb708ab182671af5653ad95">
client.personal_unlock_account(source_address, source_secret)
# => {"jsonrpc"=>"2.0", "id"=>1, "result"=>true}
erc20 = Ethereum::Contract.create(client: client, name: 'MyToken', address: contract_address, abi: contract_abi_json_string)
# => #<MyToken:0x0055cd7dea5808>
erc20.transact.transfer_from(source_address, target_address, formatter.to_wei(amount))
### IOError: authentication needed: password or unlock
```

It sends ether without problem but I'm stuck with any ERC20 token.
`source_address` is already unlocked. What else I should unlock then?

**Comment by tinbka** [comment]
Well, I got the reason. Setting `erc20.sender = source_address` and using `transfer` instead of `transfer_from` fixes this.

However, I still can't send a token.
It returns a tx like this
```
#<Ethereum::Transaction:0x0055cd7e964410 @mined=false, @connection=#<Ethereum::HttpClient:0x0055cd7de0da80 @id=0, @log=false, @batch=nil, @formatter=#<Ethereum::Formatter:0x0055cd7de0da58>, @gas_price=1000000000, @gas_limit=4000000, @host="172.16.0.16", @port=8545, @ssl=false, @uri=#<URI::HTTP http://172.16.0.16:8545>, @default_account="0x0fe7cec4eb814b884fb708ab182671af5653ad95">, @id="0xaa77d975bae8d1f63ee3787d10518f934537d7df56d1357b5cef0483488b1a96", @input="0xa9059cbb000000000000000000000000da05a6d8385ef28dff53077517add164ab75ce8600000000000000000000000000000000000000000000004ac93777298188a000", @input_parameters=["0xda05a6d8385ef28dff53077517add164ab75ce86", 1379558250000000000000]>
```

But such an id is not visible for etherscan.io. Token balances aren't changed on the local node either. Gas is not consumed as well.

**Comment by gmile** [comment]
> But such an id is not visible for etherscan.io.

Are you using `etherscan.io` or `ropsten.etherscan.io`? Also, can you double check that your node is indeed connected to the network?

**Comment by ToJen** [comment]
@tinbka i see you're using http, is that a connection to infura? If so, did you encounter `NoMethodError (undefined method `default_account' for nil:NilClass):
`

**Comment by jlstr** [comment]
Hello @tinbka!

Could you please show me what your `contract_abi_json_string` Looks like?

I am getting a **JSON::ParserError: 765: unexpected token at ''** so I assume my What I'm passing for the abi here:
```
erc20 = Ethereum::Contract.create(client: client, name: 'MyToken', address: contract_address, abi: contract_abi_json_string)
```
is somehow wrong,

Please Help!

**Comment by 5hanth** [comment]
`>  e.contract.call.transfer('0x43289a7ffDe41C1a69D10Ae31d666934859d62BE, 2)`


i just get ` => true` but nothing gets transferred. account with sender address is unlocked. 

any ideas ?

**Comment by yuriirogulya** [comment]
@5hanth, use `transact` or `transact_and_wait` instead of `call` method

**Comment by kurotaky** [comment]
@tinbka 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
