### ISSUE TITLE
Cannot send ERC20 token

### ISSUE THREAD

**Issue by gmile** [EthWorks/ethereum.rb#54]
It can't seem to successfully transfer ERC20 token from one account to another. I've published a question with details on Ethereum StackExchange, "[Cannot transfer ERC20 token, “Bad instruction” error](https://ethereum.stackexchange.com/questions/39773/cannot-transfer-erc20-token-bad-instruction-error)".

Whenever I try to send tokens between account, for some reason my transaction is qualified as **Contract Creation** (why?). And the transaction fails. Example of failed transaction is here:
 [0xe7e09fb3692fae3cf52ba58a7b52967300b83c783c0cd758a60ee6a79b1eb40c](https://ropsten.etherscan.io/tx/0xe7e09fb3692fae3cf52ba58a7b52967300b83c783c0cd758a60ee6a79b1eb40c).

Here's the code to reproduce the problem in question:

```ruby
require 'ethereum'

value = 14

account_a_address = "0xd8e05701eFf33acfDA0A8e24C04070347703c72C"
account_b_address = "0x3A70Ceac36c8111a95b573d76aD75B7ba898662b"
contract_address = "0x1caf5380b7adc2e4e93c2828f895693ff38c3947"

Ethereum::Singleton.setup do |c|
  c.default_account = account_a_address
end

Ethereum::Contract.create(
  file: "/Users/gmile/projects/ico-scripts/contracts/02-14-2018-1518620826/contract_text.sol",
  address: contract_address
)

contract = EugeneToken.new
tx = contract.transact.transfer(account_b_address, value * 1_000_000_00)

puts tx.id
```
It looks as if my ruby code tries to create a new contract instead of using existing one from the network, which is wrong. But this is how it is per Readme, e.g. [Get contract from blockchain](https://github.com/EthWorks/ethereum.rb#get-contract-from-blockchain):

> Alternatively you can obtain abi definition and name from contract source file:
>
>       contract = Ethereum::Contract.create(file: "MyContract.sol", address: 
>       "0x01a4d1A62F01ED966646acBfA8BB0b59960D06dd ")

**Comment by gmile** [comment]
Figured it out. Had to pass `contract_index` in the `#create` call.

**Comment by ToJen** [comment]
What's the `contract_index`?

**Comment by gmile** [comment]
@ToJen `contract_index` is the number of the contract in the `.sol` file. You see, the sol file may contain several contracts, such as smaller contracts which you "main" contract is comprised of.

When compiling a contract, `ethereum.rb` does not know which of the compiled contracts is your "main" one. Hence it needs a little help from your end by specifying `contract_index`.

**Comment by ToJen** [comment]
Oh right, how would you use your above code in a `..._controller.rb` file?

**Comment by gmile** [comment]
@ToJen I would put the following files into a `config/initializers/ethereum_stuff.rb`:

```ruby
account_a_address = "0xd8e05701eFf33acfDA0A8e24C04070347703c72C"
contract_address = "0x1caf5380b7adc2e4e93c2828f895693ff38c3947"

Ethereum::Singleton.setup do |c|
  c.default_account = account_a_address
end

Ethereum::Contract.create(
  file: "/path/to/contract_text.sol",
  address: contract_address
)
```

Then I would put this code into one of controller actions as desired:

```ruby
def create
  account_b_address = "0x3A70Ceac36c8111a95b573d76aD75B7ba898662b"

  contract = EugeneToken.new
  contract.transact.transfer(account_b_address, value * 1_000_000_00)
end
```

**Comment by ToJen** [comment]
Thanks @gmile  I'll try that!
