### ISSUE TITLE
Documentation outdated?

### ISSUE THREAD

**Issue by b1nary** [EthWorks/ethereum.rb#57]
I tried pretty much all i can at this point. I cant get any of the examples on how to interact with a contract to work. There simply never are any methods on call or transact.

**Comment by therevoltingx** [comment]
Are you able to deploy the `SimpleRegistry` contract and interact with it:

`contract.transact_and_wait.register("performer", "Beastie Boys")` ?

Does this throw an error? If so, could you paste the error.

Thanks.

**Comment by kurotaky** [comment]
If you are still error now, Can you show the behavior of the error in the following format?
```
### Steps to reproduce
<!-- Steps to reproduce the behavior -->

### Expected behavior
<!-- Tell us what should happen -->

### Actual behavior
<!-- Tell us what happens instead -->

### System configuration
**Ruby version**:
**Solc version**:
**Parity version**:
**OS**:

### Failure Logs
<!-- Please include any relevant log snippets or files here-->
```
