### ISSUE TITLE
Setting a default account in client

### ISSUE THREAD

**Issue by ghivert** [EthWorks/ethereum.rb#60]
Hi EthWorks!

The package works really great, but I had a little problem with the `default_account` in the client. It is the main sender for every transaction (which is great), but it's impossible to set it to the desired value. For example, when using Infura, `eth_accounts` returns an empty array. The `default_account` is always nil, which complicates things as `from: nil` when sending transactions creates bugs.

Is it possible to have a version where we can access and modify the `default_account`?

**Comment by jasonadkison** [comment]
You can set the default account it directly on the client.
[https://github.com/EthWorks/ethereum.rb/blob/master/lib/ethereum/client.rb#L14](https://github.com/EthWorks/ethereum.rb/blob/master/lib/ethereum/client.rb#L14)

You also need to set the key on the contract in order for it to be signed by your private key. See the section on signing transactions: [https://github.com/EthWorks/ethereum.rb#signed-transactions](https://github.com/EthWorks/ethereum.rb#signed-transactions)

**Comment by ToJen** [comment]
@jasonadkison how did you achieve that?

**Comment by jasonadkison** [comment]
@ToJen here's an example

```
key = Eth::Key.new(priv: YOUR_PRIVATE_KEY)
client = Ethereum::HttpClient.new(...)
client.default_account = key.address
contract = Ethereum::Contract.create(...)
contract.key = key
```

**Comment by kurotaky** [comment]
thanks for your report :)
If you still get the error, Can you show the behavior of the error in the following format?
```
### Steps to reproduce
<!-- Steps to reproduce the behavior -->

### Expected behavior
<!-- Tell us what should happen -->

### Actual behavior
<!-- Tell us what happens instead -->

### System configuration
**Ruby version**:
**Solc version**:
**Parity version**:
**OS**:

### Failure Logs
<!-- Please include any relevant log snippets or files here-->
```

**Comment by ghivert** [comment]
I'm not using this package anymore. Should the issue be closed?

**Comment by kurotaky** [comment]
@ghivert 
All right. i'm going to close this issue 👍
