### ISSUE TITLE
question re call_payload

### ISSUE THREAD

**Issue by alex-kampa** [EthWorks/ethereum.rb#62]
I'm looking for someone who could add a feature to the library, specifically just implementing the call_payload function without having to be connected to a client. The goal is to easily get the hex data necessary to prepare a sendRawTransaction call. Please contact me if interested to help. Skype = alex.kampa.

**Comment by alex-kampa** [comment]
Hello @kurotaky - just wondering: did you close because it's done, or because the issue is too old?

**Comment by kurotaky** [comment]
@alex-kampa Sorry I closed the issue because the issue was old.
Please let me know if you know anything about the call_payload implementation :)

**Comment by kurotaky** [comment]
@alex-kampa 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
