### ISSUE TITLE
How to call contract's public variable?

### ISSUE THREAD

**Issue by zulhfreelancer** [EthWorks/ethereum.rb#64]
In my contract, I have some public variables i.e. `name`, `symbol` and `decimals` like the following:

```
string public constant name    = "Cat Token";
string public constant symbol  = "CAT";
uint8 public constant decimals = 18;
```

But I'm not able to call it. I got into this error:

```
> contract.call.name()
NoMethodError: undefined method `name' for #<#<Class:0x007ff6811e7268>:0x007ff6811e7150>
	from (irb):261
	from /Users/zulh/.rvm/rubies/ruby-2.4.1/bin/irb:11:in `<main>'
```

Am I missing something here?

**Comment by ToJen** [comment]
Try making a `getName()` function that just returns name. Then call that.

**Comment by dilumn** [comment]
I think this issue is related to #67

**Comment by kurotaky** [comment]
@zulhfreelancer 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
