### ISSUE TITLE
Required dependencies

### ISSUE THREAD

**Issue by IlyaDonskikh** [EthWorks/ethereum.rb#65]
Bundle install:

``` 
   ethereum.rb was resolved to 2.0.2, which depends on
      activesupport (~> 5.0.1)
```

I can't update my rails application because of stack reasons to version `5.x.x`. Are you sure that you need version of  activesupport not lower than `5.0`.

Can you reduce the requirements for the version of `activesupport`?

**Comment by kurotaky** [comment]
activesupport dependency is higher 4.0 now. activesupport 2.0 is over.
you should upgrade to a supported version.
