### ISSUE TITLE
unrecognised option '--add-std' 

### ISSUE THREAD

**Issue by juanfer** [EthWorks/ethereum.rb#66]
Hi. I'm getting the error 

`unrecognised option '--add-std' `

when trying to create a contract using Ethereum::Contract.create. After some research it looks that solc was updated in my system from version 0.4.19 to version 0.4.21, and the new version has removed that option. I found this thread in solidity's github:

https://github.com/ethereum/solidity/issues/3695

Are you aware of it? any workaround until you fix it?

Thanks.

**Comment by jasonadkison** [comment]
It’s been addressed here: https://github.com/EthWorks/ethereum.rb/pull/61

**Comment by juanfer** [comment]
Perfect, thanks.

**Comment by ToJen** [comment]
@juanfer did the error stop showing?

**Comment by juanfer** [comment]
Hi @ToJen. Nope, I just patched my local copy until a new version of the gem rolls out. That was the only way I found to fix it in the short term.

**Comment by jasonadkison** [comment]
You can also use the master branch.

In Gemfile:
`gem 'ethereum.rb', git: 'https://github.com/ethworks/ethereum.rb.git'`

Then run `bundle update ethereum.rb`

**Comment by marekkirejczyk** [comment]
New version released, should be fixed after `bundle install`.
