### ISSUE TITLE
No such file or directory @ rb_sysopen - /tmp/ethereum_ruby_http.log

### ISSUE THREAD

**Issue by Barun-Sharma** [EthWorks/ethereum.rb#68]
I am trying to use this gem in windows, I installed ethereum node (Parity) and solidity compiler and both are running. But when I am querying 

contract = Ethereum::Contract.create(file: "greeter.sol")

I am getting below error:
No such file or directory @ rb_sysopen - /tmp/ethereum_ruby_http.log

created the file ethereum_ruby_http.log inside tmp folder in my application but still getting the same error.

can someone please let me know how to fix this issue.

**Comment by jasonadkison** [comment]
You'll need to disable logging when you create your client as that is the default behavior. If you wish to change the logging mechanism/location, you'll have to manually set the logger on the client. See [https://github.com/EthWorks/ethereum.rb/blob/433a6e895abe69c688c4b525a56843564d15f254/lib/ethereum/client.rb#L24](https://github.com/EthWorks/ethereum.rb/blob/433a6e895abe69c688c4b525a56843564d15f254/lib/ethereum/client.rb#L24)

**Comment by licolsan** [comment]
I meet the same issue, but I don't create any log file in rails project. Can you explain why?

**Comment by therevoltingx** [comment]
The problem here is that you need you disable the logs or create a `/tmp` folder.
If you don't need the logs, than the third argument to http client should be false: https://github.com/EthWorks/ethereum.rb/blob/master/lib/ethereum/http_client.rb#L7
