### ISSUE TITLE
deployed not-expected Contract

### ISSUE THREAD

**Issue by cohki0305** [EthWorks/ethereum.rb#72]
I wanted to deploy B contract like following code.

```ruby

contract = Ethereum::Contract.create(file: './B.sol', client: client)
contract.deploy_and_wait
puts contract
# => #<A:0x00007f95fd1fdb88> 
```

But the deployed contract was A. I expected B.

## solidity

```solidity
// 'B.sol'

import './A.sol';

contract B is A {}
```

```solidity
// 'A.sol'

contract A {}
```

**Comment by cohki0305** [comment]
This problem is solved by using `contract_index`?

**Comment by cohki0305** [comment]
I thought that `last` is better than `first`. In almost case, a target contract to deploy is written in bottom of a file
https://github.com/EthWorks/ethereum.rb/blob/master/lib/ethereum/contract.rb#L63

**Comment by jasonadkison** [comment]
Not sure how reliable using first or last will be. It seems like the compiled contracts may be in alphabetical order. I've worked around this by using the contract name to get the index.  [Here](https://github.com/jasonadkison/ethereum.rb/commit/05caf6cac04e4a028565f73c90871a5d4770d2ab) is my fix I've been using in production with inherited contracts without issues.

**Comment by kurotaky** [comment]
This part is currently in alphabetical order.
If you write `contract B is C {}`, calling `.first` will return B.
please If you want to specify an index, use contract_index :)
