### ISSUE TITLE
entry is not defined in events part of README

### ISSUE THREAD

**Issue by mlennie** [EthWorks/ethereum.rb#76]
args = decoder.decode_arguments(event_inputs, entry['data'])

What is entry? I tried with `decoder.decode_arguments(event_inputs,transaction["result"]["logs"][0]["data"])` but that didn't work

**Comment by kingpalethe** [comment]
Mlennie, did you figure that out? It looks like the events documentation is a rough sketch only. I am actually stuck on the line before that  
` transaction = ethereum.eth_get_transaction_receipt(transaction_id)`
Where do we get the `ethereum` instance?

**Comment by mlennie** [comment]
@kingpalethe yes I got it to work. ethereum should be client as described above in README `client = Ethereum::HttpClient.new('http://localhost:8545')`. Entry is log data for each event.

**Comment by kingpalethe** [comment]
@mlennie Thanks -- I get this
`NameError: undefined local variable or method `entry' for main:Object`
You wrote: "Entry is log data for each event". 
My event produces this data
`event Creation(uint256 indexed id, bytes32 indexed name, address factTeam);`
currently my code looks like this
`args = decoder.decode_arguments(event_inputs, entry['data'])`
How should I change it?
I tried, for example, to get the `id`:
`args = decoder.decode_arguments(event_inputs, entry['id'])`
and 
`args = decoder.decode_arguments(event_inputs, id['data'])`
But neither worked. Can you give me a hint? Many thanks.

**Comment by mlennie** [comment]
ah it's not the event data, it's the transaction logs data you get from this line `transaction = ethereum.eth_get_transaction_receipt(transaction_id)` so you can loop through transaction.logs and use the data for each log

**Comment by kingpalethe** [comment]
@mlennie Thanks much. It looks like the Readme is incorrect or out of date. I opened a new issue here:
https://github.com/EthWorks/ethereum.rb/issues/77
Were you able to get this working? If so, could you post a code sample?
