### ISSUE TITLE
Question regarding best practices

### ISSUE THREAD

**Issue by ngan** [EthWorks/ethereum.rb#78]
It looks like every time you call `Ethereum::Contract.create`, it creates a new dynamic class. We have many places in the app where we need the instances of different contracts to interact with them. Most of the time we're calling `Ethereum::Contract.create` when needed, but I'm thinking that this would result in a "memory leak" of sorts that will slowly grow the app's memory footprint.

1. I'm curious as to why there needs to be meta classes getting created for each contract? Why not just use method missing?

2. Is there a best practice to always only have 1 instance of the contract for the entire lifetime of the app and pass that around?

**Comment by yuriirogulya** [comment]
`@contract ||= Ethereum::Contract.create(params)`

**Comment by kurotaky** [comment]
@ngan 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
