### ISSUE TITLE
Ipc file not found

### ISSUE THREAD

**Issue by licolsan** [EthWorks/ethereum.rb#80]
This is my code:
`contract = Ethereum::Contract.create(file: './src/MyToken.sol')`
And this is my error:
`RuntimeError: Ipc file not found. Please pass in the file path explicitly to IpcClient initializer`
Can anyone explain and help me to solve this issue?

**Comment by Jeiwan** [comment]
You need to have an Ethereum node with IPC support running.
https://github.com/EthWorks/ethereum.rb#ipc-client-connection

**Comment by licolsan** [comment]
Thanks! @Jeiwan
