### ISSUE TITLE
Working with metamask?

### ISSUE THREAD

**Issue by licolsan** [EthWorks/ethereum.rb#82]
Can this gem connect to the metamask chrome extension?

**Comment by Jeiwan** [comment]
What do you mean by "connect to to metamask"?
MetaMask works with Ethereum nodes, so it's similar to this gem. They both do similar things but from different places: MetaMask allows you to perform operation in Ehtereum from your browser, while this gem allows you to perform operations in Ethereum from any Ruby application.

**Comment by therevoltingx** [comment]
No, metamask only works with the web3.js library.

**Comment by licolsan** [comment]
OKay, I understand. Thank you @Jeiwan and @therevoltingx :+1:

**Comment by jcserracampos** [comment]
@licolsan You can use the private generated by Metamask with this gem.
