### ISSUE TITLE
Client#transfer chain_id problems with ganache-cli

### ISSUE THREAD

**Issue by jackkinsella** [EthWorks/ethereum.rb#83]
In my test/development environments, I run ganache-cli with a specific `--networkId` (1) since I need a constancy for connecting multiple blockchain components. Unfortunately, this breaks  `Client#transfer`: https://github.com/EthWorks/ethereum.rb/blob/master/lib/ethereum/client.rb#L89

The problem seems to be that this method sets `chain_id` to the `net_version`, which, confusingly, seems to bear no relation to the network id I initialized ganache-cli with.

I was able to get things working by hardcoding my network id of 1:
```ruby
def transfer(...)
  Eth.configure { |c| c.chain_id = 1  }
   ...
end
```

I confess I don't yet fully grok the difference between chain id and network id, but I do know that this problem would be solved for me if the signature of transfer was modified to accept an optional `chain_id` param.

**Comment by jsperezg** [comment]
@jackkinsella I'm facing the same issue.

**Comment by kurotaky** [comment]
@jackkinsella 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
