### ISSUE TITLE
How to decode event data for events with indexed arguments

### ISSUE THREAD

**Issue by addywaddy** [EthWorks/ethereum.rb#88]
Firstly - thanks for this repository! It's been a real help for me getting started with Ethereum, coming from the ruby world.

I have question regarding decoding events, specificallly events with indexed arguments.

parsing the data for an event such as:

```
Transfer(address from, address to, uint256 amount)
```
works find, but as soon as any arguments are indexed, it barfs out an Argument error (in the below case from 'decode_address')

```
Transfer(address indexed from, address indexed to, uint256 amount)
```
I see that the repository has some example contracts which also have indexed arguments in the events, so I presume I must be doing something wrong here. Any pointers most welcome!

**Comment by gen1321** [comment]
I have same issue
