### ISSUE TITLE
client.transfer should accept data as argument

### ISSUE THREAD

**Issue by nileshtrivedi** [EthWorks/ethereum.rb#95]
`client.transfer` method currently always sets `data` in transaction to be a blank string. This should be added as (optional?) method argument.

**Comment by q9f** [comment]
No, a _"transfer"_ is just the means of sending Ether from account A to address B. Transfers do not have any data. Never.

If you want to call a contract or write an ASCII message to the blockchain, you'll just make a custom transaction.

**Comment by kurotaky** [comment]
@nileshtrivedi 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
