### ISSUE TITLE
Cannot deploy with private key

### ISSUE THREAD

**Issue by Nu-hin** [EthWorks/ethereum.rb#97]
If you use remote Ethereum provider, like Infura, you can only send signed transactions. Therefore, if I want to deploy contract, I need to sign transaction locally. However Rake task `ethereum:contract:deploy` always uses singleton client, and I see no way to set `key` parameter for `Contract` in this case.

**Comment by kurotaky** [comment]
@Nu-hin 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
